# SwiftLint Configuration for Brad OS
# Philosophy: no warnings. A thing either matters (error) or it doesn't (off).

# Only lint project source files
included:
  - BradOS
  - BradOSCore/Sources
  - BradOSWidget
  - BradOSWatch

excluded:
  - BradOSCore/Tests
  - "**/*.generated.swift"
  - build
  - DerivedData
  - .build

# Analyzer rules (require full compilation)
analyzer_rules:
  - unused_import

# Opt-in rules we care about (all enforced as errors)
opt_in_rules:
  - force_unwrapping
  - empty_count
  - empty_string
  - closure_spacing
  - contains_over_filter_count
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - last_where
  - modifier_order
  - overridden_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - toggle_bool
  - vertical_whitespace_closing_braces

disabled_rules:
  - todo
  - trailing_comma
  - opening_brace
  - multiple_closures_with_trailing_closure
  - for_where
  - unneeded_parentheses_in_closure_argument
  - fallthrough
  - implicit_getter

# Rule configurations — errors only, no warnings
# For threshold rules, set warning = error to eliminate the warning band

force_unwrapping:
  severity: error

force_cast:
  severity: error

force_try:
  severity: error

discouraged_optional_boolean:
  severity: error

redundant_type_annotation:
  severity: error

vertical_whitespace_closing_braces:
  severity: error

empty_count:
  severity: error

empty_string:
  severity: error

closure_spacing:
  severity: error

contains_over_filter_count:
  severity: error

contains_over_first_not_nil:
  severity: error

fatal_error_message:
  severity: error

first_where:
  severity: error

flatmap_over_map_reduce:
  severity: error

last_where:
  severity: error

modifier_order:
  severity: error

overridden_super_call:
  severity: error

redundant_nil_coalescing:
  severity: error

toggle_bool:
  severity: error

function_body_length:
  warning: 60
  error: 60

cyclomatic_complexity:
  warning: 15
  error: 15

file_length:
  warning: 600
  error: 600
  ignore_comment_only_lines: true

type_body_length:
  warning: 500
  error: 500

line_length:
  warning: 200
  error: 200
  ignores_comments: true
  ignores_urls: true
  ignores_interpolated_strings: true

nesting:
  type_level: 3
  function_level: 3

identifier_name:
  min_length:
    warning: 2
    error: 2
  max_length:
    warning: 60
    error: 60
  excluded:
    - id
    - x
    - y
    - i
    - j
    - k
    - to
    - vc
    - vm
    - ok
    - db

large_tuple:
  warning: 4
  error: 4

reporter: xcode
