name: BradOS
options:
  bundleIdPrefix: com.bradcarter
  deploymentTarget:
    iOS: "17.0"
    watchOS: "10.0"
  xcodeVersion: "15.0"
  groupSortPosition: top

packages:
  BradOSCore:
    path: BradOSCore
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    version: 11.0.0
  SwiftLintPlugins:
    url: https://github.com/SimplyDanny/SwiftLintPlugins
    from: 0.63.2

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,4"
    INFOPLIST_FILE: BradOS/Info.plist
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    DEVELOPMENT_TEAM: TWWJ3E2WLY
    CODE_SIGN_STYLE: Automatic
    CODE_SIGN_IDENTITY: "Apple Development"

targets:
  BradOS:
    type: application
    platform: iOS
    sources:
      - path: BradOS
        excludes:
          - "*.xcassets"
          - "Resources/Audio"
          - "GoogleService-Info.plist"
      - path: BradOS/Assets.xcassets
      - path: BradOS/Resources/Audio
        type: folder
        buildPhase: resources
      - path: BradOS/GoogleService-Info.plist
        buildPhase: resources
    dependencies:
      - package: BradOSCore
      - package: Firebase
        product: FirebaseAppCheck
      - target: BradOSWidget
      - target: BradOSWatch
    buildToolPlugins:
      - plugin: SwiftLintBuildToolPlugin
        package: SwiftLintPlugins
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bradcarter.brad-os
        PRODUCT_NAME: "Brad OS"
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: false
        INFOPLIST_FILE: BradOS/Info.plist
        CODE_SIGN_ENTITLEMENTS: BradOS/BradOS.entitlements
    info:
      path: BradOS/Info.plist
      properties:
        UILaunchScreen:
          UIColorName: LaunchBackground
        UIUserInterfaceStyle: Dark
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIBackgroundModes:
          - audio
        LSApplicationQueriesSchemes:
          - spotify
        NSHealthShareUsageDescription: We use your HRV, sleep, and weight data to track recovery and provide personalized cycling training recommendations.
        NSRemindersFullAccessUsageDescription: BradOS uses Reminders to export your weekly grocery shopping list.
        NSUserNotificationsUsageDescription: BradOS uses notifications to alert you when rest timers complete during workouts.
        NSCameraUsageDescription: BradOS uses the camera to scan and identify food items for calorie tracking.
        CFBundleURLTypes:
          - CFBundleURLName: com.bradcarter.brad-os
            CFBundleURLSchemes:
              - brados

  BradOSWidget:
    type: app-extension
    platform: iOS
    sources:
      - path: BradOSWidget
        excludes:
          - "*.entitlements"
    dependencies:
      - package: BradOSCore
    buildToolPlugins:
      - plugin: SwiftLintBuildToolPlugin
        package: SwiftLintPlugins
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bradcarter.brad-os.widget
        CODE_SIGN_ENTITLEMENTS: BradOSWidget/BradOSWidget.entitlements
        TARGETED_DEVICE_FAMILY: "1,4"
        GENERATE_INFOPLIST_FILE: false
        INFOPLIST_FILE: BradOSWidget/Info.plist
    info:
      path: BradOSWidget/Info.plist
      properties:
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension

  BradOSWatch:
    type: application
    platform: watchOS
    sources:
      - path: BradOSWatch
        excludes:
          - "*.entitlements"
    buildToolPlugins:
      - plugin: SwiftLintBuildToolPlugin
        package: SwiftLintPlugins
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bradcarter.brad-os.watchkitapp
        PRODUCT_NAME: "Brad OS Watch"
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        WATCHOS_DEPLOYMENT_TARGET: "10.0"
        TARGETED_DEVICE_FAMILY: "4"
        CODE_SIGN_ENTITLEMENTS: BradOSWatch/BradOSWatch.entitlements
        GENERATE_INFOPLIST_FILE: false
        INFOPLIST_FILE: BradOSWatch/Info.plist
    info:
      path: BradOSWatch/Info.plist
      properties:
        WKCompanionAppBundleIdentifier: com.bradcarter.brad-os
        WKApplication: true
        WKRunsIndependentlyOfCompanionApp: false
        UIBackgroundModes:
          - workout-processing
        NSHealthShareUsageDescription: Brad OS reads your heart rate during workouts to display real-time metrics.
        NSHealthUpdateUsageDescription: Brad OS records workout sessions and calories burned to Apple Health.

schemes:
  BradOS:
    build:
      targets:
        BradOS: all
        BradOSWidget: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  BradOSWatch:
    build:
      targets:
        BradOSWatch: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
