export {
  type MockDocumentSnapshot,
  type MockQueryDocumentSnapshot,
  type MockQuerySnapshot,
  type FirestoreMocks,
  type UserScopedFirestoreMocks,
  type MockFirestoreQuery,
  createMockDoc,
  createMockQuerySnapshot,
  createMockQuery,
  createFirestoreQueryChain,
  createFirestoreMocks,
  createUserScopedFirestoreMocks,
  setupFirebaseMock,
} from './firestore-mock.js';
